from swarm import Agent

from .prompts import (
    skeleton_writer_agent_prompt,
    skeleton_reviewer_prompt,
    content_writer_agent_prompt,
    content_reviewer_prompt,
)
from .setup import model
from .tools.call_llm import call_llm
from .tools.web_search import web_search

skeleton_writer_agent = Agent(
    name="Skeleton Writer Agent",
    model=model,
    instructions=skeleton_writer_agent_prompt,
    # tool_choice="required",
)

content_writer_agent = Agent(
    name="Content Writer Agent",
    model=model,
    instructions=content_writer_agent_prompt
)

def submit_skeleton_for_review(skeleton: str) -> str:
    """
    Submits a skeleton for review.

    Args:
        skeleton (str): The skeleton content to be reviewed.

    Returns:
        str: The review response generated by the LLM.
    """
    return call_llm(prompt=skeleton_reviewer_prompt+skeleton)

def submit_final_skeleton():
    """
    Submits the final version of a skeleton.
    """
    return content_writer_agent

def submit_content_for_review(content: str) -> str:
    """
    Submits a generated post content for review.

    Args:
        content (str): The post content to be reviewed.

    Returns:
        str: The review response generated by the LLM.
    """
    return call_llm(prompt=content_reviewer_prompt+content)

def edit_skeleton():
    """
    Call this function if the user doesn't like the generated skeleton or wants to change the structure.
    """
    return skeleton_writer_agent

skeleton_writer_agent.functions=[submit_skeleton_for_review, web_search, submit_final_skeleton]

content_writer_agent.functions=[submit_content_for_review, edit_skeleton]